baseURL: https://vanshaj.xyz/
languageCode: en-us
languages:
  en:
    disabled: false
theme: ["PaperMod"]
title: "@vanshaj.xyz" # site title displayed at the top of home page

taxonomies:
  topic: topics
  tag: tags
  category: categories

enableSearch: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
