env: development
title: "Vanshaj Saxena"
description: A site by Vanshaj Saxena.
author: ["Vanshaj Saxena"]

homeInfoParams:
  Title: Vanshaj Saxena
  Content: A Developer, and a geek. I am passionate about [Read more...]({{< relref "about.md" >}})

profileMode:
  enabled: false
  title: "Vanshaj Saxena" # optional default will be site title
  subtitle: "Java | Linux"
  imageUrl: "/PSX_20240914_225243.jpg"
  imageTitle: "Vanshaj Saxena" # optional
  imageWidth: 120 # custom size
  imageHeight: 120 # custom size
  buttons:
    - name: Projects
      url: "/projects"
    - name: About
      url: "https://vanshaj.xyz/about"

socialIcons:
  - name: "GitHub"
    url: "https://github.com/VanshajSaxena"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/vanshajsaxena2024"
  - name: "Email"
    url: "mailto:vs110405@outlook.com"

defaultTheme: auto
languageAltTitle: English
showCodeCopyButtons: true
disableSpecial1stPost: true
hideSummary: false
showtoc: true
tocopen: false
useHugotoc: false
showBreadCrumbs: true
showPostNavLinks: false
showSharebuttons: false
showWordCount: false
shareButtons: [linkedin, x]
ShowRssButtonInSectionTermList: true
comments: true
hideFooter: true
ShowCanonicalLink: true
displayFullLangName: true
# keywords: ["sitekeyword1", "sitekeyword2"]
# label.text: labelText
cover:
  - responsiveImages: true
mainSections:
  - posts # only show blog posts on the Home Info page
# # for search
# fuseOpts:
#   isCaseSensitive: false
#   shouldSort: true
#   location: 0
#   distance: 1000
#   threshold: 0.4
#   minMatchCharLength: 0
#   limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
#   keys: ["title", "permalink", "summary", "content"] ##  can be less but not more than shown in list
