[build]
publish = "public"
command = "hugo --gc --minify --environment $HUGO_ENV"

[context.deploy-preview]
command = "echo 'BUILD CONTEXT IS: deploy-preview' && echo 'HUGO_ENV IS:' $HUGO_ENV && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "echo 'BUILD CONTEXT IS: branch-preview' && echo 'HUGO_ENV IS:' $HUGO_ENV && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[build.environment]
HUGO_VERSION = "0.155.3"
HUGO_ENV = "preview"

[build.processing]
skip_node_bundling = true

[context.production]
environment = { HUGO_ENV = "production", HUGO_ENABLEGITINFO = "true" }

[[headers]]
for = "/css/giscus-*.css"
[headers.values]
Access-Control-Allow-Origin = "https://giscus.app"
